/* ═══════════════════════════════════════════════════════════════════════
   Collab protocol validation (§28) — zod schemas for EVERY client→server
   frame. The hub dispatches ONLY through these parsers: unknown types,
   wrong shapes, oversized payloads and forged identity fields are rejected
   BEFORE any room/session state is touched, so a malformed frame can never
   crash the room or the WebSocket server.

   Rules:
     - identity is NEVER accepted from the client (userId/permissions are
       derived server-side from the socket's authenticated user) — there is
       no schema field for them by construction.
     - binary payloads (s64/u64) are bounded (base64 length cap) so a
       hostile client cannot allocate unbounded buffers per frame.
     - pageId/objectId strings are bounded and pattern-checked (page ids are
       'p<N>' ordinals, persisted pid attrs or runtime ids — all printable,
       no control chars).
     - document payloads (the persistence 'doc' frame) are shape-checked
       (type:'doc', bounded content) — never logged (§29: no document
       content in logs).
   ═══════════════════════════════════════════════════════════════════════ */

import { z } from 'zod';

/** base64 cap ≈ a full-document update can be large, but a single yjs
 *  incremental update frame is realistically << 8 MB */
const MAX_B64 = 8 * 1024 * 1024;
const b64 = z.string().max(MAX_B64).regex(/^[A-Za-z0-9+/=]*$/, 'not base64');
/** page ids / session ids: printable, bounded, no whitespace or control
 *  characters (ids are generated by this system or derived from persisted
 *  attrs; anything else is a forged frame) */
const id = z.string().min(1).max(128).regex(/^[A-Za-z0-9_\-:.]+$/);

/** every schema is strict: unknown/forged fields (userId, permissions,
 *  sessionId claims, …) REJECT the frame instead of being silently
 *  stripped — identity is server-derived only (§27) */
const frame = (t: z.ZodLiteral<any>, shape: z.ZodRawShape) => z.object({ t, ...shape }).strict();

export const clientFrameSchema = z.discriminatedUnion('t', [
  frame(z.literal('join'), { noteId: id, sessionId: id.optional() }),
  frame(z.literal('heartbeat'), { pageId: id.optional() }),
  frame(z.literal('acquire'), {}),
  frame(z.literal('sync.step1'), { s64: b64 }),
  frame(z.literal('sync.step2'), { u64: b64 }),
  frame(z.literal('update'), { u64: b64 }),
  frame(z.literal('awareness'), { u64: b64 }),
  frame(z.literal('doc'), {
    /** §4 storage shape check — the projection/persistence reads content +
        floatingElements; deep TipTap node validation stays the client's
        autosave contract (the room never parses the whole tree). Nested
        content is NOT strict (arbitrary TipTap node shapes) but the frame
        envelope itself is. */
    doc: z.object({ type: z.literal('doc') }).passthrough(),
  }),
  frame(z.literal('metadata'), { title: z.string().max(300) }),
  frame(z.literal('leave'), {}),
]);

export type ClientFrame = z.infer<typeof clientFrameSchema>;

/** Parse a raw client frame. Returns null for ANY malformed input — the
 *  hub treats null as "drop silently" (never crash, never log content). */
export function parseClientFrame(raw: string): ClientFrame | null {
  let json: unknown;
  try { json = JSON.parse(raw); } catch { return null; }
  const parsed = clientFrameSchema.safeParse(json);
  return parsed.success ? parsed.data : null;
}
