import { chromium } from 'playwright-core';
const BASE = 'http://[::1]:5199';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.setDefaultTimeout(45000);
const res = await page.request.post(BASE + '/api/auth/login', { data: { email: 'demo@pernote.local', password: 'demo1234' } });
const { token } = await res.json();
await page.goto(BASE + '/login', { waitUntil: 'load' });
await page.evaluate((t) => localStorage.setItem('pn_token', t), token);
await page.goto(BASE + '/editor/new', { waitUntil: 'load' });
await page.waitForSelector('[data-ribbon-root]', { timeout: 30000 });
await page.waitForTimeout(1200);
const chip = await page.evaluate(() => {
  const btn = document.querySelector('[aria-label^="حساب کاربری"]');
  if (!btn) return null;
  const cs = getComputedStyle(btn);
  return { round: cs.borderRadius, size: btn.clientWidth, hasDot: btn.innerHTML.includes('0070f3') || btn.innerHTML.includes('ff5b4f') };
});
console.log('CHIP:', JSON.stringify(chip));
await page.click('[aria-label^="حساب کاربری"]');
await page.waitForTimeout(300);
const menu = await page.evaluate(() => {
  const m = document.querySelector('[role=menu]');
  if (!m) return null;
  return { hasText: !!m.textContent, items: [...m.querySelectorAll('[role=menuitem]')].map((x) => x.textContent?.trim()) };
});
console.log('CHIP MENU:', JSON.stringify(menu));
await page.click('[role=menuitem]');
await page.waitForTimeout(700);
console.log('NAV:', page.url().includes('/settings') ? 'goes-to-settings PASS' : 'FAIL ' + page.url());
await page.screenshot({ path: '../qa-editor-chip.png' });
await browser.close();
